export class TimezoneAndLocation{
    
    public static geolocationListData(){
        return [{value:"japan",name:'Japan'},
        {value:"americas", name: 'Americas'},
        {value:"apac", name:'APAC'},
        {value:"china", name:'China'},
        {value:"emea",name:'EMEA'}]
    }

    public static timezoneListData(){
        return [{ value:"International Date Line West",option:"Pacific/Midway"},
        {value:"Midway Island",option:"Pacific/Midway"},
        { value:"American Samoa",option:"Pacific/Pago_Pago"},
        { value:"Hawaii",option:"Pacific/Honolulu"},
        { value:"Alaska",option:"America/Juneau"},
        { value:"Pacific Time (US &amp; Canada)",option:"America/Los_Angeles"},
        { value:"Tijuana",option:"America/Tijuana"},
        { value:"Mountain Time (US &amp; Canada)",option:"America/Denver"},
        { value:"Arizona",option:"America/Phoenix"},
        { value:"Chihuahua",option:"America/Chihuahua"},
        { value:"Mazatlan",option:"America/Mazatlan"},
        { value:"Central Time (US &amp; Canada)",option:"America/Chicago"},
        { value:"Saskatchewan",option:"America/Regina"},
        { value:"Guadalajara",option:"America/Mexico_City"},
        { value:"Mexico City",option:"America/Mexico_City"},
        { value:"Monterrey",option:"America/Monterrey"},
        { value:"Central America",option:"America/Guatemala"},
        { value:"Eastern Time (US &amp; Canada)",option:"America/New_York"},
        { value:"Indiana (East)",option:"America/Indiana/Indianapolis"},
        { value:"Bogota",option:"America/Bogota"},
        { value:"Lima",option:"America/Lima"},
        { value:"Quito",option:"America/Lima"},
        { value:"Atlantic Time (Canada)",option:"America/Halifax"},
        { value:"Caracas",option:"America/Caracas"},
        { value:"La Paz",option:"America/La_Paz"},
        { value:"Santiago",option:"America/Santiago"},
        { value:"Newfoundland",option:"America/St_Johns"},
        { value:"Brasilia",option:"America/Sao_Paulo"},
        { value:"Buenos Aires",option:"America/Argentina/Buenos_Aires"},
        { value:"Montevideo",option:"America/Montevideo"},
        { value:"Georgetown",option:"America/Guyana"},
        { value:"Greenland",option:"America/Godthab"},
        { value:"Mid-Atlantic",option:"Atlantic/South_Georgia"},
        { value:"Azores",option:"Atlantic/Azores"},
        { value:"Cape Verde Is.",option:"Atlantic/Cape_Verde"},
        { value:"Dublin",option:"Europe/Dublin"},
        { value:"Edinburgh",option:"Europe/London"},
        { value:"Lisbon",option:"Europe/Lisbon"},
        { value:"London",option:"Europe/London"},
        { value:"Casablanca",option:"Africa/Casablanca"},
        { value:"Monrovia",option:"Africa/Monrovia"},
        { value:"UTC",option:"Etc/UTC"},
        { value:"Belgrade",option:"Europe/Belgrade"},
        { value:"Bratislava",option:"Europe/Bratislava"},
        { value:"Budapest",option:"Europe/Budapest"},
        { value:"Ljubljana",option:"Europe/Ljubljana"},
        { value:"Prague",option:"Europe/Prague"},
        { value:"Sarajevo",option:"Europe/Sarajevo"},
        { value:"Skopje",option:"Europe/Skopje"},
        { value:"Warsaw",option:"Europe/Warsaw"},
        { value:"Zagreb",option:"Europe/Zagreb"},
        { value:"Brussels",option:"Europe/Brussels"},
        { value:"Copenhagen",option:"Europe/Copenhagen"},
        { value:"Madrid",option:"Europe/Madrid"},
        { value:"Paris",option:"Europe/Paris"},
        { value:"Amsterdam",option:"Europe/Amsterdam"},
        { value:"Berlin",option:"Europe/Berlin"},
        { value:"Bern",option:"Europe/Zurich"},
        { value:"Zurich",option:"Europe/Zurich"},
        { value:"Rome",option:"Europe/Rome"},
        { value:"Stockholm",option:"Europe/Stockholm"},
        { value:"Vienna",option:"Europe/Vienna"},
        { value:"West Central Africa",option:"Africa/Algiers"},
        { value:"Bucharest",option:"Europe/Bucharest"},
        { value:"Cairo",option:"Africa/Cairo"},
        { value:"Helsinki",option:"Europe/Helsinki"},
        { value:"Kyiv",option:"Europe/Kiev"},
        { value:"Riga",option:"Europe/Riga"},
        { value:"Sofia",option:"Europe/Sofia"},
        { value:"Tallinn",option:"Europe/Tallinn"},
        { value:"Vilnius",option:"Europe/Vilnius"},
        { value:"Athens",option:"Europe/Athens"},
        { value:"Istanbul",option:"Europe/Istanbul"},
        { value:"Minsk",option:"Europe/Minsk"},
        { value:"Jerusalem",option:"Asia/Jerusalem"},
        { value:"Harare",option:"Africa/Harare"},
        { value:"Pretoria",option:"Africa/Johannesburg"},
        { value:"Kaliningrad",option:"Europe/Kaliningrad"},
        { value:"Moscow",option:"Europe/Moscow"},
        { value:"St. Petersburg",option:"Europe/Moscow"},
        { value:"Volgograd",option:"Europe/Volgograd"},
        { value:"Samara",option:"Europe/Samara"},
        { value:"Kuwait",option:"Asia/Kuwait"},
        { value:"Riyadh",option:"Asia/Riyadh"},
        { value:"Nairobi",option:"Africa/Nairobi"},
        { value:"Baghdad",option:"Asia/Baghdad"},
        { value:"Tehran",option:"Asia/Tehran"},
        { value:"Abu Dhabi",option:"Asia/Muscat"},
        { value:"Muscat",option:"Asia/Muscat"},
        { value:"Baku",option:"Asia/Baku"},
        { value:"Tbilisi",option:"Asia/Tbilisi"},
        { value:"Yerevan",option:"Asia/Yerevan"},
        { value:"Kabul",option:"Asia/Kabul"},
        { value:"Ekaterinburg",option:"Asia/Yekaterinburg"},
        { value:"Islamabad",option:"Asia/Karachi"},
        { value:"Karachi",option:"Asia/Karachi"},
        { value:"Tashkent",option:"Asia/Tashkent"},
        { value:"Chennai",option:"Asia/Kolkata"},
        { value:"Kolkata",option:"Asia/Kolkata"},
        { value:"Mumbai",option:"Asia/Kolkata"},
        { value:"New Delhi",option:"Asia/Kolkata"},
        { value:"Kathmandu",option:"Asia/Kathmandu"},
        { value:"Astana",option:"Asia/Dhaka"},
        { value:"Dhaka",option:"Asia/Dhaka"},
        { value:"Sri Jayawardenepura",option:"Asia/Colombo"},
        { value:"Almaty",option:"Asia/Almaty"},
        { value:"Novosibirsk",option:"Asia/Novosibirsk"},
        { value:"Rangoon",option:"Asia/Rangoon"},
        { value:"Bangkok",option:"Asia/Bangkok"},
        { value:"Hanoi",option:"Asia/Bangkok"},
        { value:"Jakarta",option:"Asia/Jakarta"},
        { value:"Krasnoyarsk",option:"Asia/Krasnoyarsk"},
        { value:"Beijing",option:"Asia/Shanghai"},
        { value:"Chongqing",option:"Asia/Chongqing"},
        { value:"Hong Kong",option:"Asia/Hong_Kong"},
        { value:"Urumqi",option:"Asia/Urumqi"},
        { value:"Kuala Lumpur",option:"Asia/Kuala_Lumpur"},
        { value:"Singapore",option:"Asia/Singapore"},
        { value:"Taipei",option:"Asia/Taipei"},
        { value:"Perth",option:"Australia/Perth"},
        { value:"Irkutsk",option:"Asia/Irkutsk"},
        { value:"Ulaanbaatar",option:"Asia/Ulaanbaatar"},
        { value:"Seoul",option:"Asia/Seoul"},
        { value:"Osaka",option:"Asia/Tokyo"},
        { value:"Sapporo",option:"Asia/Tokyo"},
        { value:"Tokyo",option:"Asia/Tokyo"},
        { value:"Yakutsk",option:"Asia/Yakutsk"},
        { value:"Darwin",option:"Australia/Darwin"},
        { value:"Adelaide",option:"Australia/Adelaide"},
        { value:"Canberra",option:"Australia/Melbourne"},
        { value:"Melbourne",option:"Australia/Melbourne"},
        { value:"Sydney",option:"Australia/Sydney"},
        { value:"Brisbane",option:"Australia/Brisbane"},
        { value:"Hobart",option:"Australia/Hobart"},
        { value:"Vladivostok",option:"Asia/Vladivostok"},
        { value:"Guam",option:"Pacific/Guam"},
        { value:"Port Moresby",option:"Pacific/Port_Moresby"},
        { value:"Magadan",option:"Asia/Magadan"},
        { value:"Srednekolymsk",option:"Asia/Srednekolymsk"},
        { value:"Solomon Is.",option:"Pacific/Guadalcanal"},
        { value:"New Caledonia",option:"Pacific/Noumea"},
        { value:"Fiji",option:"Pacific/Fiji"},
        { value:"Kamchatka",option:"Asia/Kamchatka"},
        { value:"Marshall Is.",option:"Pacific/Majuro"},
        { value:"Auckland",option:"Pacific/Auckland"},
        { value:"Wellington",option:"Pacific/Auckland"},
        { value:"Nuku",option:"Pacific/Tongatapu"},
        { value:"Tokelau Is.",option:"Pacific/Fakaofo"},
        { value:"Chatham Is.",option:"Pacific/Chatham"},
        { value:"Samoa",option:"Pacific/Apia"}]
    }
    
}